[package]
name = "mock_app"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
reqwest = { version = "0.12.22", features = ["json"] }
tokio = { version = "1.47.1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
serde_json = "1.0.145"
